### restart vagrant VMs
- hosts: localhost
  become: false
  max_fail_percentage: 0

  tasks:
    - name: vagrant up
      shell: vagrant up
      when: "'microsoft-standard' not in ansible_kernel"

    - name: vagrant up (for WSL2)
      shell: vagrant.exe up
      when: "'microsoft-standard' in ansible_kernel"

  environment:
    VAGRANT_CWD: "{{ playbook_dir }}/vagrant"
    WSLENV: VAGRANT_CWD/p:http_proxy:https_proxy


### restart VirtualBMC
- import_playbook: ./ansible-virtualbmc/20-vbmc-start.yml

### restart Pacemaker
- import_playbook: ./ansible-pacemaker-rocky8/20-pacemaker-start.yml


