### stop vagrant VMs
- hosts: localhost
  become: false
  max_fail_percentage: 0

  tasks:
    - name: vagrant halt
      shell: vagrant halt
      when: "'microsoft-standard' not in ansible_kernel"

    - name: vagrant halt (for WSL2)
      shell: vagrant.exe halt
      when: "'microsoft-standard' in ansible_kernel"

  environment:
    VAGRANT_CWD: "{{ playbook_dir }}/vagrant"
    WSLENV: VAGRANT_CWD/p:http_proxy:https_proxy


### stop VirtualBMC
- import_playbook: ./ansible-virtualbmc/90-vbmc-stop.yml


